export const RandomPrompts = [
    "Craft a clay-style profile avatar showcasing a stylish young boy deeply connected to the world of hip hop. The medium of choice should be clay, providing a tangible and textured aesthetic. Infuse the avatar with elements inspired by the street art of Jean-Michel Basquiat, combining vibrant colors and raw expression. Illuminate the scene with a soft, warm spotlight, creating an urban ambiance. Choose a color palette that encompasses bold graffiti hues, like vivid blues, energetic yellows, and fiery reds. Opt for a close-up composition, capturing the boy's confident gaze and his headphones adorned with graffiti-inspired designs. Use a wide-angle lens to accentuate the details of his outfit, emphasizing the urban streetwear and hip hop fashion.",
    "Craft a mesmerizing close-up artwork that focuses solely on a pair of eyes, evoking mystery and intrigue. Employ a hyper-realistic style using oil paints, capturing every intricate detail of the eyes. Play with contrasting lighting, casting half of the face in deep shadows while illuminating the eyes with a single beam of ethereal blue light. Use a macro lens to magnify the eyes, emphasizing the reflection of distant stars in their deep, dark irises. The color palette should consist of rich blues, purples, and hints of silver, creating an otherworldly atmosphere that transports the viewer to a cosmic realm",
    "Sculpt A Captivating Profile Avatar For A Girl Who Immerses Herself In The Digital Realm, Spending Hours On End Engrossed In Her Laptop. Craft The Character From Clay, Infusing Her With A Contemplative And Focused Expression. Utilize A Color Palette That Combines Cool Tones With Pops Of Vibrant Hues To Represent The Digital Environment. Position The Girl In A Relaxed Sitting Pose, With Her Legs Crossed And Laptop Placed On Her Lap. Pay Attention To The Details, Such As The Texture Of Her Hair, Clothing, And The Laptop Itself. Surround Her With Symbolic Elements Like Icons And Symbols Floating In The Air, Representing The Virtual World She Delves Into. Use Lighting To Create A Gentle Glow, Casting Soft Shadows That Add Depth And Dimension To The Clay Artwork.",
    "Imagine A Supercar That Embodies The Perfect Fusion Of Speed, Luxury, And Cutting-Edge Technology. Design An Electrifying Profile Avatar For The Supercar, Showcasing Its Sleek And Aerodynamic Form. The Car Should Possess A Glossy Exterior In A Vibrant And Eye-Catching Color, Such As Metallic Silver Or Fiery Red. Highlight Its Aggressive Features, Including Sharp Angles, A Low-Slung Body, And A Prominent Front Grille. Incorporate Futuristic Design Elements, Such As LED Lights, Sleek Alloy Wheels, And Streamlined Curves. Imagine The Supercar In A Dynamic Pose, Captured Mid-Action, As If Zooming Along A Winding Mountain Road. Use Dynamic Lighting To Accentuate Its Contours And Emphasize The Play Of Shadows And Reflections.",
    "Imagine a bustling market square in a medieval town with merchants and performers",
    "Construct a mythical creature, combining features of different animals in a unique way",
    "Sculpt a serene garden with blooming flowers and tranquil water features",
    "Develop a space station orbiting a distant planet, complete with astronauts and alien life",
    "Design an otherworldly landscape on an alien planet with strange rock formations",
    "Create a steampunk-inspired airship floating in the clouds",
    "Generate a futuristic robot that performs a specific task in an advanced society",
    "Craft a magical forest glade with fairies and glowing plants",
    "Design an ancient temple hidden deep within a lush jungle",
    "Imagine a group of explorers discovering a lost city in the desert",
    "Create a bustling harbor with ships of various sizes and sailors going about their tasks",
    "Sculpt a mythical creature that guards a hidden treasure in a mystical cave",
    "Develop a floating island in the sky with floating waterfalls and floating trees",
    "Craft a post-apocalyptic wasteland with crumbling buildings and overgrown vegetation",
    "Design an enchanted winter wonderland with ice sculptures and a frozen lake",
    "Create a vibrant coral reef teeming with exotic fish and sea turtles"
]
